# Copyright The ozone-oidc-proxy Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: ozpx-prometheus
    editable: false
